name: Test Authentication Service

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go 1.16.x
        uses: actions/setup-go@v3
        with:
          go-version-file: authentication-service/go.mod
          cache: true
          cache-dependency-path: authentication-service/go.sum

      - name: Test Auth Service
        run: |
          cd authentication-service
          go test ./...
